version: "3"

services:

  #gitlab container - upload the build
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "22:22"
      - "80:80"
      
    enviroment:
      - "GITLAB_SKIP_UNMIGRATED_DATA_CHECK=true"

    volumes:
      - "gl-config:/etc/gitlab"
      - "gl-logs:/var/log/gitlab"
      - "gl-data:/var/opt/gitlab"

# use jenkins dockerfile with docker inside, build CI\CD tool
  jenkins:
    #image : jenkins/jenkins:lts-jdk8 
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - "jenkins_home2:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    
  #artifactory container to upload (delivery) the app
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.16.0
    ports:
      - "8081:8081"
    volumes:
      - "art-data:/var/opt/jfrog/artifactory"



volumes:
  gl-config:
  gl-logs:
  gl-data:
  jenkins_home2:
  art-data: